name: Docker
description: |
  Base docker build/push action
inputs:
  path:
    description: "relative path to the place where source code with Dockerfile is located"
    required: false
    default: "."
  keep_last:
    description: "Number of docker tags to keep on the container registry"
    required: false
    default: "10"
  registry:
    description: "Registry host"
    required: false
    default: "ghcr.io"
  filter_files:
    required: false
    default: |
      - "**"
    description: |
      Run only if certain files changed. Syntax is a yaml list:
      ```
      - common/**
      - config/**
      ```
  ALL_SECRETS:
    description: "Secrets to inject"
    required: true
  OTHER_ENVS:
    description: "Other envs to inject"
    required: false
outputs:
  docker_tag:
    description: "The docker tag that was pushed"
    value: ${{ jobs.build.outputs.docker_tag }}

runs:
  using: "composite"
  steps:
    - name: To deploy
      id: to_deploy
      uses: NearSeaTechnologies/workflows/should-deploy@1.5.0
      with:
        ALL_SECRETS: ${{ secrets.ALL_SECRETS }}
        OTHER_ENVS: ${{ secrets.OTHER_ENVS }}

    - uses: dorny/paths-filter@v2.10.2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          docker:
          ${{ inputs.filter_files }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: steps.filter.outputs.docker == 'true' || steps.to_deploy.outputs.should_deploy == 'true'

    - id: repo_lower
      uses: ASzc/change-string-case-action@v1
      if: steps.filter.outputs.docker == 'true' || steps.to_deploy.outputs.should_deploy == 'true'
      with:
        string: ${{ github.repository }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      if: steps.filter.outputs.docker == 'true' || steps.to_deploy.outputs.should_deploy == 'true'
      env:
        cache_tag: buildcache
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ${{ inputs.path }}
        # Note: tags has to be all lower-case
        tags: |
          ${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ github.sha }}
          ${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:latest
          ${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ steps.to_deploy.outputs.env_name }}
        push: ${{ github.event_name != 'pull_request' && steps.to_deploy.outputs.should_deploy == 'true' }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ env.cache_tag }}
        cache-to: type=registry,ref=${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ env.cache_tag }},mode=max

    - id: tag_output
      shell: bash
      if: steps.filter.outputs.docker == 'true' || steps.to_deploy.outputs.should_deploy == 'true'
      run: echo "::set-output name=tag::${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ github.sha }}"
