name: 'Deploy envs'
description: |
  Checks if there should be a deploy for this branch, by checking if there are env vars with the corresponding prefix.
    Ex.: Branch test/first has a prefix of "__TEST__*".
  That's stored on the output should_deploy.
  It also injects the secrets into the GITHUB_ENV, if the input is true
inputs:
  inject_envs:
    description: 'If the environment variables should be injects (without the prefix)'
    required: false
    default: 'false'
outputs:
  should_deploy:
    description: "If there should be a deploy for this branch"
    value: ${{ steps.to_deploy.outputs.has_envs }}
  env_name:
    description: "The extracted env name (uppercase)"
    value: ${{ steps.extract_env_name.outputs.env_name }}

runs:
  using: "composite"
  steps:
    - name: Get env name
      shell: bash
      run: echo "##[set-output name=env_name;]$(echo ${GITHUB_BASE_REF:-$GITHUB_REF_NAME} | grep -o '^[^/]*' | tr a-z A-Z)"
      id: extract_env_name

    - name: Create .env and .env.output.envs
      uses: shine1594/secrets-to-env-action@v1.5.2
      with:
        secrets: ${{ secrets.ALL_SECRETS }}
        secrets_env: all
        # Get all secrets as .env
        prefix_prod: _${{ steps.extract_env_name.outputs.env_name }}_
        file_name_prod: terraform/.env

    - name: Load .env
      shell: bash
      if: inputs.inject_envs == 'true'
      run: |
        # Inject all secrets as envs (for this env)
        (cat terraform/.env) >> $GITHUB_ENV

    - name: To deploy
      shell: bash
      run: |
        echo "##[set-output name=has_envs;]$([ -s terraform/.env ] && echo true)"
      id: to_deploy
