name: Docker
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."
      keep_last:
        description: "Number of docker tags to keep on the container registry"
        required: false
        type: string
        default: "10"
      registry_host:
        description: "Registry host"
        required: false
        type: string
        default: "ghcr.io"
      prune:
        description: "If it should prune old entries (works for GitHub or DigitalOcean)"
        required: false
        type: boolean
        default: true
      registry_cache:
        description: "If the registry should be used for cache instead of GitHub's cache"
        required: false
        type: boolean
        default: false
      exclude_prune:
        description: "Tags to exclude, on the prune"
        required: false
        type: string
        default: "DEVELOP|RELEASE|MASTER"
      filter_files:
        required: false
        type: string
        default: |
          - "**"
        description: |
          Run only if certain files changed. Syntax is a yaml list:
          ```
          - common/**
          - config/**
          ```
      always_run:
        description: If it should run for every push or only on Merge Requests and deployment branches
        required: false
        type: boolean
        default: false
    secrets:
      username:
        description: "Registry username"
        required: true
      password:
        description: "Registry password"
        required: true
      ALL_SECRETS:
        required: true
      OTHER_ENVS:
        required: false
      PERSONAL_GITHUB_TOKEN:
        required: true
    outputs:
      docker_tag:
        description: "The docker tag that was pushed"
        value: ${{ jobs.build.outputs.docker_tag }}

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  cache_tag: buildcache

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.docker.outputs.docker_tag }}
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry_host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - id: repo_lower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Build/push docker image
        id: docker
        uses: NearSeaTechnologies/workflows/docker@1.8.0
        with:
          path: ${{ inputs.path }}
          registry_repository: ${{ inputs.registry_host }}/${{ steps.repo_lower.outputs.lowercase }}
          filter_files: ${{ inputs.filter_files }}
          registry_cache: ${{ inputs.registry_cache }}
          ALL_SECRETS: ${{ secrets.ALL_SECRETS }}
          OTHER_ENVS: ${{ secrets.OTHER_ENVS }}
          always_run: ${{ inputs.always_run }}

      - name: GHCR Prune
        uses: freefair/action-ghcr-prune@v0.4.1
        if: inputs.prune == true && steps.docker.outputs.should_skip != 'true' && (steps.docker.outputs.docker_filter == 'true' || steps.docker.outputs.should_deploy == 'true')
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          keep-last: ${{ inputs.keep_last }}
          tag-regex-exclude: \b(?:latest|${{ env.cache_tag }}|${{ inputs.exclude_prune }})\b
          untagged: true