name: Docker
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."
    secrets:
      ALL_SECRETS:
        required: true
      PERSONAL_GITHUB_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  cache_tag: buildcache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - id: repo_lower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: To deploy
        id: to_deploy
        uses: NearSeaTechnologies/terraform-cicd/should-deploy@feature/docker-pipeline
        with:
          ALL_SECRETS: ${{ secrets.ALL_SECRETS }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ${{ inputs.path }}
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/${{ steps.repo_lower.outputs.lowercase }}:${{ github.sha }}
            ghcr.io/${{ steps.repo_lower.outputs.lowercase }}:latest
          push: ${{ steps.to_deploy.outputs.should_deploy == 'true' }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo_lower.outputs.lowercase }}:${{ env.cache_tag }}
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo_lower.outputs.lowercase }}:${{ env.cache_tag }},mode=max

      - name: GHCR Prune
        uses: freefair/action-ghcr-prune@v0.4.1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          keep-last: 10
          tag-regex-exclude: \b(?:latest|${{ env.cache_tag }})\b
          untagged: true
