name: Docker
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."
      keep_last:
        description: "Number of docker tags to keep on the container registry"
        required: false
        type: string
        default: "10"
      registry:
        description: "Registry host"
        required: false
        type: string
        default: "ghcr.io"
      filter_files:
        required: false
        type: string
        default: |
          - "**"
        description: |
          Run only if certain files changed. Syntax is a yaml list:
          ```
          - common/**
          - config/**
          ```
    secrets:
      ALL_SECRETS:
        required: true
      OTHER_ENVS:
        required: false
      PERSONAL_GITHUB_TOKEN:
        required: true
      username:
        description: "Registry username"
        required: true
      password:
        description: "Registry password"
        required: true
    outputs:
      docker_tag:
        description: "The docker tag that was pushed"
        value: ${{ jobs.build.outputs.docker_tag }}

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  cache_tag: buildcache

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.tag_output.outputs.tag }}
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker:
            ${{ inputs.filter_files }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.filter.outputs.docker == 'true'

      - name: Login to Github Packages
        uses: docker/login-action@v1
        if: steps.filter.outputs.docker == 'true'
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - id: repo_lower
        uses: ASzc/change-string-case-action@v1
        if: steps.filter.outputs.docker == 'true'
        with:
          string: ${{ github.repository }}

      - name: To deploy
        id: to_deploy
        uses: NearSeaTechnologies/workflows/should-deploy@1.5.0
        if: steps.filter.outputs.docker == 'true'
        with:
          ALL_SECRETS: ${{ secrets.ALL_SECRETS }}
          OTHER_ENVS: ${{ secrets.OTHER_ENVS }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        if: steps.filter.outputs.docker == 'true'
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ${{ inputs.path }}
          # Note: tags has to be all lower-case
          tags: |
            ${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ github.sha }}
            ${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:latest
          push: ${{ github.event_name != 'pull_request' && steps.to_deploy.outputs.should_deploy == 'true' }}
          cache-from: type=registry,ref=${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ env.cache_tag }}
          cache-to: type=registry,ref=${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ env.cache_tag }},mode=max

      - id: tag_output
        if: steps.filter.outputs.docker == 'true'
        run: echo "::set-output name=tag::${{ inputs.registry }}/${{ steps.repo_lower.outputs.lowercase }}:${{ github.sha }}"

      - name: GHCR Prune
        uses: freefair/action-ghcr-prune@v0.4.1
        if: steps.filter.outputs.docker == 'true'
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          keep-last: ${{ inputs.keep_last }}
          tag-regex-exclude: \b(?:latest|${{ env.cache_tag }})\b
          untagged: true
