name: Docker
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."
      keep_last:
        description: "Number of docker tags to keep on the container registry"
        required: false
        type: string
        default: "10"
      registry_endpoint:
        description: "Registry endpoint"
        required: true
        type: string
      prune:
        description: "If it should prune old entries (works for GitHub or DigitalOcean)"
        required: false
        type: boolean
        default: true
      exclude_prune:
        description: "Tags to exclude, on the prune"
        required: false
        type: string
        default: "DEVELOP|RELEASE|MASTER"
      filter_files:
        required: false
        type: string
        default: |
          - "**"
        description: |
          Run only if certain files changed. Syntax is a yaml list:
          ```
          - common/**
          - config/**
          ```
    secrets:
      ALL_SECRETS:
        required: true
      OTHER_ENVS:
        required: false
      DIGITALOCEAN_ACCESS_TOKEN:
        description: "Digital ocean access token for prune (if DO's container registry is used)"
        required: false
    outputs:
      docker_tag:
        description: "The docker tag that was pushed"
        value: ${{ jobs.build.outputs.docker_tag }}

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  cache_tag: buildcache

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.docker.outputs.docker_tag }}
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - id: repo_lower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - uses: jungwinter/split@master
        id: split
        with:
          msg: ${{ steps.repo_lower.outputs.lowercase }}
          separator: "/"
          maxsplit: 1

      - name: Build/push docker image
        id: docker
        uses: NearSeaTechnologies/workflows/docker@1.7.6-rc18
        with:
          path: ${{ inputs.path }}
          keep_last: ${{ inputs.keep_last }}
          registry_repository: ${{ inputs.registry_endpoint }}/${{ steps.split.outputs._1 }}
          filter_files: ${{ inputs.filter_files }}
          ALL_SECRETS: ${{ secrets.ALL_SECRETS }}
          OTHER_ENVS: ${{ secrets.OTHER_ENVS }}

      - name: DigitalOcean Registry Prune Old Tags
        if: inputs.prune == true && (steps.docker.outputs.docker_filter == 'true' || steps.to_deploy.outputs.should_deploy == 'true')
        uses: PierreAndreis/do-registry-prune-tags@1.0.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
