name: CI
on:
  workflow_call:
    secrets:
      terraform_cloud_tokens:
        required: false

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: terraform validate
        uses: dflook/terraform-validate@v1.25.0
        with:
          path: terraform
        env:
          TERRAFORM_CLOUD_TOKENS: ${{ secrets.terraform_cloud_tokens }}

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.25.0
        with:
          path: terraform
        env:
          TERRAFORM_CLOUD_TOKENS: ${{ secrets.terraform_cloud_tokens }}
  
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Render terraform docs inside the terraformDocs.md
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: terraform
          output-file: ../terraformDocs.md
          output-method: inject
          git-push: ${{ github.event_name != 'pull_request' && github.ref_name == 'develop' }}

      - name: Comment docs on PR
        uses: NejcZdovc/comment-pr@v1
        if: github.event_name == 'pull_request'
        with:
          file: "../../terraformDocs.md"