name: Terraform Plan/apply
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "terraform"
      filter_files:
        required: false
        type: string
        default: |
          - "**"
        description: |
          Run only if certain files changed. Syntax is a yaml list:
          ```
          - common/**
          - config/**
          ```
      inject_other_envs:
        required: false
        type: boolean
        default: false
    secrets:
      ALL_SECRETS:
        required: true
      OTHER_ENVS:
        required: false
      terraform_cloud_tokens:
        required: false

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Plan/apply terraform
    timeout-minutes: 5
    steps:
      - name: Git checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: To deploy
        id: to_deploy
        uses: NearSeaTechnologies/workflows/should-deploy@1.5.0
        with:
          inject_secrets: true
          inject_other_envs: ${{ inputs.inject_other_envs }}
          ALL_SECRETS: ${{ secrets.ALL_SECRETS }}
          OTHER_ENVS: ${{ secrets.OTHER_ENVS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        if: steps.to_deploy.outputs.should_deploy == 'true'
        with:
          cli_config_credentials_token: ${{ secrets.terraform_cloud_tokens }}

      - name: Terraform Init
        id: init
        if:  steps.to_deploy.outputs.should_deploy == 'true'
        run: terraform -chdir=${{ inputs.path }} init -input=false

      - name: Terraform Plan
        id: plan
        if:  steps.to_deploy.outputs.should_deploy == 'true' && github.event_name == 'pull_request'
        run: terraform -chdir=${{ inputs.path }} plan -no-color -input=false
        continue-on-error: true

      - name: Comment docs on PR
        uses: NejcZdovc/comment-pr@v1
        if:  steps.to_deploy.outputs.should_deploy == 'true' && github.event_name == 'pull_request'
        with:
          identifier: plan
          message: |
            #### Terraform Initialization ⚙️`${{ steps.init.outcome }}`
            #### Terraform Plan 📖`${{ steps.plan.outcome }}`

            <details><summary>Show Plan</summary>

            ```
            terraform

            ${{ steps.plan.outputs.stdout }}
            ```

            </details>

            *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`, Working Directory: `${{ inputs.path }}`, Workflow: `${{ github.workflow }}`*

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: steps.to_deploy.outputs.should_deploy == 'true' && github.event_name != 'pull_request'
        run: terraform -chdir=${{ inputs.path }} apply -auto-approve -input=false